version: "3.9"

services:
  db:
    image: postgres
    hostname: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    env_file:
      - docker/.env-non-dev

  app:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - docker/.env-non-dev
    container_name: app
    command: [ "/app/docker/main.sh" ]
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
